name: CI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["2.9.1"]
        ghc: ["9.2.5"]
    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          stack-version: ${{ matrix.stack }}

      - uses: actions/cache@v3
        id: cache-stack
        name: Cache ~/.stack
        with:
          path: ~/.stack
          # key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack
          restore-keys: |
            ${{ runner.os }}-stack-global-

      - name: Install dependencies
        if: steps.cache-stack.outputs.cache-hit != 'true'
        run: |
          stack build --no-run-tests --no-run-benchmarks --only-dependencies

      - name: Build
        if: steps.cache-stack.outputs.cache-hit == 'true'
        run: |
          stack build
          stack exec myblog clean
          stack exec myblog build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/master'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch